### ISSUE TITLE
Problem resolving rosdep dependency

### ISSUE THREAD

**Issue by biancofla** [myyerrol/learning_moveit#1]
Hi.
I'm trying to build the catkin workspace, but I encounter this dependency problem:
>> rosdep install -y --from-paths . --ignore-src --rosdistro kinetic
Output: ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
learning_moveit: Cannot locate rosdep definition for [panda_moveit_motion_planning]

Currently, I'm running Ubuntu 16.04 with Ros Kinetic.

**Comment by myyerrol** [comment]
@biancofla Thanks for asking problem! I have fixed this bug. you can use **`git pull`**  command to get lastest code. In addition, because I'm still updating the contents of the repository, it is expected that it will be finished a few weeks later, so if you are not in a hurry, you can wait until I finish finally.

**Comment by biancofla** [comment]
Sure, I can wait :) Btw, thanks to the fix, now the Gazebo simulation works great :+1:
